export enum EventType {
  CONNECTED = 'CONNECTED',
  RECONNECTED = 'RECONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  HEARTBEAT_MISSED = 'HEARTBEAT_MISSED',
  HEARTBEAT_RESUMED = 'HEARTBEAT_RESUMED',
}
