export enum RoomCloseReason {
  TIME_ELAPSED = 'TIME_ELAPSED',
  HOST_CLOSED = 'HOST_CLOSED',
  LAST_LEARNER_LEFT = 'LAST_LEARNER_LEFT',
  AFK_FORCED_END = 'AFK_FORCED_END',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
}
