export enum BookingOrigin {
  MENTOR_POST = 'MENTOR_POST',
  LEARNER_REQUEST = 'LEARNER_REQUEST',
}

export enum BookingStatus {
  PENDING_MENTOR_APPROVAL = 'PENDING_MENTOR_APPROVAL',
  PENDING_LEARNER_APPROVAL = 'PENDING_LEARNER_APPROVAL',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}
