export enum ReportCategory {
  TOXIC_LANGUAGE = 'TOXIC_LANGUAGE',
  FRAUD = 'FRAUD',
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  SPAM = 'SPAM',
  AFK_ABUSE = 'AFK_ABUSE',
  OTHER = 'OTHER',
}
