export enum TrustChangeReason {
  SESSION_COMPLETED = 'SESSION_COMPLETED',
  RATING_5_STAR = 'RATING_5_STAR',
  RATING_4_STAR = 'RATING_4_STAR',
  RATING_2_STAR = 'RATING_2_STAR',
  RATING_1_STAR = 'RATING_1_STAR',
  LAST_MINUTE_CANCEL = 'LAST_MINUTE_CANCEL',
  AFK_REPORTED = 'AFK_REPORTED',
  NO_SHOW = 'NO_SHOW',
  TOXIC_LANGUAGE = 'TOXIC_LANGUAGE',
  FRAUD = 'FRAUD',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
