export enum EntryType {
  ESCROW_HOLD = 'ESCROW_HOLD',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  HEARTBEAT_DEDUCT = 'HEARTBEAT_DEDUCT',
  TRIAL_REFUND = 'TRIAL_REFUND',
  CANCELLATION_REFUND = 'CANCELLATION_REFUND',
  AFK_REFUND = 'AFK_REFUND',
  ONBOARDING_REWARD = 'ONBOARDING_REWARD',
  MODERATION_REFUND = 'MODERATION_REFUND',
}
