export enum RewardGrantType {
  REGISTER = 'REGISTER',
  PROFILE_COMPLETE = 'PROFILE_COMPLETE',
  STREAK_REWARD = 'STREAK_REWARD',
  PROFILE_AVATAR = 'PROFILE_AVATAR',
  PROFILE_SKILL = 'PROFILE_SKILL',
  PROFILE_BIO = 'PROFILE_BIO',
}
