export enum CancellationReason {
  MENTOR_BUSY = 'MENTOR_BUSY',
  LEARNER_BUSY = 'LEARNER_BUSY',
  SYSTEM_AFK = 'SYSTEM_AFK',
  MUTUAL_AGREE = 'MUTUAL_AGREE',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
}
