export enum RewardType {
  REGISTER = 'REGISTER',
  PROFILE_COMPLETE = 'PROFILE_COMPLETE',
  STREAK_DAY_1 = 'STREAK_DAY_1',
  STREAK_DAY_2 = 'STREAK_DAY_2',
  STREAK_DAY_3 = 'STREAK_DAY_3',
  STREAK_DAY_4 = 'STREAK_DAY_4',
  STREAK_DAY_5 = 'STREAK_DAY_5',
  STREAK_DAY_6 = 'STREAK_DAY_6',
  STREAK_DAY_7 = 'STREAK_DAY_7',
  PROFILE_AVATAR = 'PROFILE_AVATAR',
  PROFILE_SKILL = 'PROFILE_SKILL',
  PROFILE_BIO = 'PROFILE_BIO',
}
