export enum FailureReason {
  NONE = 'NONE',
  DEVICE_UNREGISTERED = 'DEVICE_UNREGISTERED',
  PROVIDER_DOWN = 'PROVIDER_DOWN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  RATE_LIMITED = 'RATE_LIMITED',
  USER_OPTED_OUT = 'USER_OPTED_OUT',
}
