export enum NotificationKind {
  BOOKING_REMINDER_15M = 'BOOKING_REMINDER_15M',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_ACCEPTED = 'BOOKING_ACCEPTED',
  BOOKING_REJECTED = 'BOOKING_REJECTED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  POST_NEW_FROM_FOLLOWED_MENTOR = 'POST_NEW_FROM_FOLLOWED_MENTOR',
  WALLET_LOW_BALANCE = 'WALLET_LOW_BALANCE',
  WALLET_REWARD_GRANTED = 'WALLET_REWARD_GRANTED',
  TRUST_SCORE_TIER_CHANGED = 'TRUST_SCORE_TIER_CHANGED',
  MODERATION_RESULT = 'MODERATION_RESULT',
}
